### ISSUE TITLE
PHP multibyte string

### ISSUE THREAD

**Issue by puck3000** [jalenconner/craftbox#1]
Hello
I installed craftbox and when trying to access craft on 192.168.33.10 it tells me:

"Craft CMS requires the PHP multibyte string extension in order to run. Please talk to your host/IT department about enabling it on your server."

What did go wrong?

**Comment by jalenconner** [comment]
@puck3000 Hmm... seems like Craftbox isn't installing the PHP multibyte string extension which is required to run Craft (https://craftcms.com/docs/requirements#required-php-extensions). Let me see if I am able to replicate it on my end. Thanks for the heads-up and sorry it isn't working for you 😟

**Comment by jalenconner** [comment]
@puck3000 Alright, I have fixed the bug. So to update, please re-download Craftbox and then replace the provisioning folder in your project with the provisioning folder from the download. Then you will need to run `vagrant provision` in your project. That should fix it!
Again sorry for the inconvenience and thanks for letting me know!

**Comment by puck3000** [comment]
Thank you a lot for taking your time to fix this! much appreciated!
I'll test it tonight and report back…

best regards

**Comment by jalenconner** [comment]
@puck3000 Just wanted to check in and see how Craftbox was working for you? Did the update fix your problem?
